In [45]:
import seaborn as sns
import pandas as pd

In [161]:
df = sns.load_dataset('tips')
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [162]:
df['time']

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [163]:
# First we will convert categorical columns into numerical one using one hot encoding.

In [164]:
from sklearn.preprocessing import OneHotEncoder

In [165]:
categorical_columns = ['sex','smoker','day']
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

df_encoded = pd.concat([df, one_hot_df], axis=1)

df_encoded = df_encoded.drop(categorical_columns, axis=1)

In [166]:
categorical_columns

['sex', 'smoker', 'day']

In [167]:
#df_encoded = pd.get_dummies(df,dtype=int)

In [168]:
df_encoded

,total_bill,tip,time,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Dinner,2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,10.34,1.66,Dinner,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
2,21.01,3.50,Dinner,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,23.68,3.31,Dinner,2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,24.59,3.61,Dinner,4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Dinner,3,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
240,27.18,2.00,Dinner,2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
241,22.67,2.00,Dinner,2,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
242,17.82,1.75,Dinner,2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
243,18.78,3.00,Dinner,2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [169]:
X = df_encoded.iloc[:,:-2]

In [195]:
X = X.drop('time',axis=1)

In [206]:
X

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat
0,16.99,1.01,2,1.0,0.0,1.0,0.0,0.0,0.0
1,10.34,1.66,3,0.0,1.0,1.0,0.0,0.0,0.0
2,21.01,3.50,3,0.0,1.0,1.0,0.0,0.0,0.0
3,23.68,3.31,2,0.0,1.0,1.0,0.0,0.0,0.0
4,24.59,3.61,4,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,0.0,1.0,1.0,0.0,0.0,1.0
240,27.18,2.00,2,1.0,0.0,0.0,1.0,0.0,1.0
241,22.67,2.00,2,0.0,1.0,0.0,1.0,0.0,1.0
242,17.82,1.75,2,0.0,1.0,1.0,0.0,0.0,1.0
243,18.78,3.00,2,1.0,0.0,1.0,0.0,0.0,0.0

In [196]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [197]:
df['output_encoded'] = le.fit_transform(df['time'])

In [198]:
y = df.iloc[:,-1]

In [199]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: output_encoded, Length: 244, dtype: int64

In [200]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [201]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [202]:
gnb.fit(X_train,y_train)

GaussianNB()

In [203]:
y_pred = gnb.predict(X_test)

In [204]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [205]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[28  0]
 [27 19]]
0.6351351351351351
              precision    recall  f1-score   support

           0       0.51      1.00      0.67        28
           1       1.00      0.41      0.58        46

    accuracy                           0.64        74
   macro avg       0.75      0.71      0.63        74
weighted avg       0.81      0.64      0.62        74